version: '3'

volumes:
  db:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '$PWD/sqlConf'
  rootHost:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '$PWD/scripts'
  jupyterConfig:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '$PWD/jupyterConf'

services:
  orcapp:
    image: quay.io/plotly/orca
    links:
      - jupyter
      - stockbot
    restart: always
  # postgres:
  #   image: postgres:latest
  #   restart: always
  #   #ports:
  #   #  - 8237:5432
  #   volumes:
  #     - db:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_USER=root
  #     - POSTGRES_PASSWORD=SsD8SQDU8JisJ9sqd_2

  stockbot:
    image: pythonstock:latest
    build:
      context: ./dockerpython
      dockerfile: ./Dockerfile
    # links:
    #   - postgres
    volumes:
      - rootHost:/datajupyter
    restart: always
    working_dir: /datajupyter
    entrypoint: "/venv/bin/python stock_bot.py"

  jupyter:
    image: jupyterstock:latest
    build:
      context: ./dockerjupyter
      dockerfile: ./Dockerfile
    ports:
      - 8388:8888
    # links:
      # - postgres
    volumes:
      - rootHost:/datajupyter
      - jupyterConfig:/home/user/.jupyter
    restart: always
    working_dir: /datajupyter
    entrypoint: "/venv/bin/jupyter lab --port=8888 --no-browser --ip=0.0.0.0 --allow-root"


  stockapp:
    image: dockerdash:latest
    build:
        context: ./dockerdash
        dockerfile: ./Dockerfile
    ports:
      - 8389:8050
    #links:
    #  - postgres
    volumes:
      - rootHost:/datajupyter
    restart: always
    working_dir: /datajupyter
    entrypoint: "/venv/bin/python main-stocks.py"



