version: '3'

volumes:
  db:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/comptadecac/stocktools/store-sql'
  rootHost:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/comptadecac/stocktools/scripts'
  jupyterConfig:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/comptadecac/stocktools/jupyterconfig'

services:
  pgSQLapp:
    image: postgres:latest
    restart: always
    #ports:
    #  - 8237:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=SsD8SQDU8JisJ9sqd_2

  jupyterimage:
    image: pythondocker:latest
    build:
      context: ./pythondocker
      dockerfile: ./Dockerfile
    ports:
      - 8388:8888
    links:
      - pgSQLapp
    volumes:
      - rootHost:/datajupyter
      - jupyterConfig:/home/user/.jupyter
    restart: always
    working_dir: /datajupyter
    entrypoint: "/home/user/venv/bin/jupyter lab --port=8888 --no-browser --ip=0.0.0.0 --allow-root"


  stockapp:
    image: pythondocker:latest
    ports:
      - 8389:8050
    links:
      - pgSQLapp
    volumes:
      - rootHost:/datajupyter
    restart: always
    working_dir: /datajupyter
    entrypoint: "/home/user/venv/bin/python main-stocks.py"


  stockbot:
    image: pythondocker:latest
    links:
      - pgSQLapp
    volumes:
      - rootHost:/datajupyter
    restart: always
    working_dir: /datajupyter
    entrypoint: "/home/user/venv/bin/python stock_bot.py"



  orcapp:
    image: quay.io/plotly/orca
    links:
      - jupyterimage
      - stockbot
    restart: always


