"""init

Revision ID: 032b09dcbe46
Revises: 
Create Date: 2020-02-19 19:59:33.984540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '032b09dcbe46'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stockday',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stockname', sa.String(), nullable=False),
    sa.Column('datestamp', sa.Date(), nullable=False),
    sa.Column('priceOpen', sa.Float(), nullable=True),
    sa.Column('priceHigh', sa.Float(), nullable=True),
    sa.Column('priceLow', sa.Float(), nullable=True),
    sa.Column('priceClose', sa.Float(), nullable=True),
    sa.Column('priceAdjClose', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stockintraday',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stockname', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stockname')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stockintraday')
    op.drop_table('stockday')
    # ### end Alembic commands ###
