"""init

Revision ID: a5f8012e5889
Revises: 032b09dcbe46
Create Date: 2020-02-19 20:27:27.460473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5f8012e5889'
down_revision = '032b09dcbe46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stockday', sa.Column('dateadded', sa.DateTime(), nullable=True))
    op.add_column('stockintraday', sa.Column('dateadded', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stockintraday', 'dateadded')
    op.drop_column('stockday', 'dateadded')
    # ### end Alembic commands ###
