"""init

Revision ID: 1a0608a8e319
Revises: 
Create Date: 2020-03-03 20:56:47.207585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a0608a8e319'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('histdetectstockvar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stockname', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('dataorigin', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stockday',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stockname', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('priceOpen', sa.Float(), nullable=True),
    sa.Column('priceHigh', sa.Float(), nullable=True),
    sa.Column('priceLow', sa.Float(), nullable=True),
    sa.Column('priceClose', sa.Float(), nullable=True),
    sa.Column('priceAdjClose', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('dateadded', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stockintraday',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stockname', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('priceOpen', sa.Float(), nullable=True),
    sa.Column('priceHigh', sa.Float(), nullable=True),
    sa.Column('priceLow', sa.Float(), nullable=True),
    sa.Column('priceClose', sa.Float(), nullable=True),
    sa.Column('priceAdjClose', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('dateadded', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stockintraday')
    op.drop_table('stockday')
    op.drop_table('histdetectstockvar')
    # ### end Alembic commands ###
